# Generated by Django 6.0.2 on 2026-02-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='slug',
        ),
    ]
